/*
* This source file was generated by the Gradle 'init' task
*/
package org.example

import org.example.resto.Persona
import org.example.resto.Fecha

fun main(){
    println(Persona("Malena", "Masi", Fecha(28, 1, 2010)))
}