/*
* This source file was generated by the Gradle 'init' task
*/
package org.example
import org.example.Persona
import org.example.Fecha
import org.example.Polinomio

fun main() {

    var t1 = Termino(2,2)
    var t2 = Termino(4,1)
    var t3 = Termino(-3,0)

    var pol1 = Polinomio (arrayListOf(t3,t2,t1))

    var t4 = Termino(3,3)
    var t5 = Termino(-4,2)
    var t6 = Termino(-7,1)
    var t7 = Termino(5,0)

    var pol2 = Polinomio (arrayListOf(t7,t6,t5,t4))

    println(pol1)

    println(pol2)

    var polSuma = pol1.sumar(pol2)
    println(polSuma)
}